import type { Metadata } from 'next';
import { ThemeProvider } from 'next-themes';
import AppShell from '@/components/app-shell';
import './globals.css';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

interface RootLayoutProps {
	children: React.ReactNode;
}

export default function RootLayout({ children }: Readonly<RootLayoutProps>) {
	return (
		<html
			suppressHydrationWarning
			lang="en"
		>
			<body>
				<ThemeProvider
					enableSystem
					attribute="class"
					defaultTheme="system"
					themes={['light', 'dark']}
				>
					<AppShell>{children}</AppShell>
				</ThemeProvider>
			</body>
		</html>
	);
}
